// <auto-generated />
using System;
using BlazorWEBAppTestingPhilip.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorWEBAppTestingPhilip.Migrations.Todo
{
    [DbContext(typeof(TodoContext))]
    partial class TodoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("BlazorWEBAppTestingPhilip.Models.Cpr", b =>
                {
                    b.Property<int>("Cprid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CprNr")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("User")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Cprid")
                        .HasName("PK__Cpr__C0242C1E474FB435");

                    b.ToTable("Cpr", (string)null);
                });

            modelBuilder.Entity("BlazorWEBAppTestingPhilip.Models.TodoList", b =>
                {
                    b.Property<int>("TodoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("todoId");

                    b.Property<string>("Item")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("item");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TodoId")
                        .HasName("PK__TodoList__E5C578A19823DF68");

                    b.HasIndex("UserId");

                    b.ToTable("TodoList", (string)null);
                });

            modelBuilder.Entity("BlazorWEBAppTestingPhilip.Models.TodoList", b =>
                {
                    b.HasOne("BlazorWEBAppTestingPhilip.Models.Cpr", "User")
                        .WithMany("TodoLists")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__TodoList__UserId__267ABA7A");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BlazorWEBAppTestingPhilip.Models.Cpr", b =>
                {
                    b.Navigation("TodoLists");
                });
#pragma warning restore 612, 618
        }
    }
}
